package org.Des2;

public class Campos_PgAtm_Out {

	/*
	 * PKG_ATM.PRO_ATM
	 * 
	*/
	
	private String MSGTYPE;
	private String C2_TARJETA;
	private String C3_PROCCODE;
	private String C4_MONTO;
	private String C5_MONTO_SETTLEMENT;
	private String C6_MONTO_CARDBILL;
	private String C7_DATETIME;
	private String C8_MONTO_CARDBILLFEE;
	private String C9_CONVER_RATE_SETTLEMENT;
	private String C10_CONVER_RATE_CARDBILL;
	private String C11_AUDIT_NUMBER;
	private String C12_HORA_TRAN;
	private String C13_FECHA_TRAN;
	private String C14_EXP_DATE;
	private String C15_DATE_SETTLEMENT;
	private String C16_DATE_CONVERSION;
	private String C17_DATE_CAPTURE;
	private String C18_MERCHANT_TYPE;
	private String C19_ADQ_INST_COUTRY_CODE;
	private String C20_PAN_COUNTRY_CODE;
	private String C21_FORW_INST_COUNTRY_CODE;
	private String C22_POS_ENTRY_MODE;
	private String C23_CARD_SEQ_NUMBER;
	private String C24_NETWORK_ID;
	private String C25_POS_COND_CODE;
	private String C26_POS_PIN_CAPTURE_CODE;
	private String C27_AUTH_RESPONSE_LENGTH;
	private String C28_MONTO_TRANS_FEE;
	private String C29_MONTO_SETTLEMENT_FEE;
	private String C30_MONTO_TRANS_PROC_FEE;
	private String C31_MONTO_SETTLEMENT_PROC_FEE;
	private String C32_ACQ_INST_ID;
	private String C33_FORW_INST_ID;
	private String C34_PAN_EXTENDED;
	private String C35_TRACK2;
	private String C36_TRACK3;
	private String C37_REFERENCE_NUMBER;
	private String C38_AUTORIZACION;
	private String C39_RESP_CODE;
	private String C40_SERV_RESTRICTION_CODE;
	private String C41_TERMINAL_ID;
	private String C42_CARD_ACCEPTOR_ID;
	private String C43_CARD_ACCEPTOR_NAME_LOC;
	private String C44_ADDITIONAL_RESP_DATA;
	private String C45_TRACK1;
	private String C46_ADDITIONAL_DATA_ISO_USE;
	private String C47_ADDITIONAL_DATA_NAT_USE;
	private String C48_ADDITIONAL_DATA_PRIV_USE;
	private String C49_CURRENCY_CODE;
	private String C50_CURRENCY_CODE_SETTLEMENT;
	private String C51_CURRENCY_CODE_CARDBILL;
	private String C52_PIN_DATA;
	private String C53_SECURITY_RELATE_INF;
	private String C54_ADDITIONAL_AMOUNTS;
	private String C55_ICC_SYSTEM;
	private String C56_RESERVED_ISO;
	private String C57_RESERVED_NATIONAL_USE;
	private String C58_RESERVED_NATIONAL_USE;
	private String C59_NAT_GEO_DATA;
	private String C60_ADVICE_REASON_CODE;
	private String C61_POS_DATA;
	private String C62_INT_NETWORK_FACILITY_DATA;
	private String C63_BANKNET_DATA;
	private String C64_MESSAGE_AUTH_CODE;
	private String C65_BITMAP_EXTENDED;
	private String C66_SETTLEMENT_CODE;
	private String C67_EXTENDED_PAYMENT_CODE;
	private String C68_RECV_INST_COUNTRY_CODE;
	private String C69_SETTL_INST_COUNTRY_CODE;
	private String C70_NET_INFORMATION_CODE;
	private String C71_MESSAGE_NUMBER;
	private String C72_MESSAGE_NUMBER_LAST;
	private String C73_DATE_ACTION;
	private String C74_CREDITS_NUMBER;
	private String C75_CREDITS_REVERSAL_NUMBER;
	private String C76_DEBITS_NUMBER;
	private String C77_DEBITS_REVERSAL_NUMBER;
	private String C78_TRANSFERS_NUMBER;
	private String C79_TRANSFERS_REVERSAL_NUMBER;
	private String C80_INQUIRIES_NUMBER;
	private String C81_AUTHORIZATION_NUMBER;
	private String C82_CREDITS_PROC_FEE_AMOUNT;
	private String C83_CREDITS_TRAN_FEE_AMOUNT;
	private String C84_DEBITS_PROC_FEE_AMOUNT;
	private String C85_DEBITS_TRAN_FEE_AMOUNT;
	private String C86_CREDITS_AMOUNT;
	private String C87_CREDITS_REVERSAL_AMOUNT;
	private String C88_DEBITS_AMOUNT;
	private String C89_DEBITS_REVERSAL_AMOUNT;
	private String C90_ORIGINAL_DATA;
	private String C91_FILE_UPDATE_CODE;
	private String C92_FILE_SECURITY_CODE;
	private String C93_RESPONSE_INDICATOR;
	private String C94_SERVICE_INDICATOR;
	private String C95_REPLACEMENT_AMOUNTS;
	private String C96_MESSAGE_SECURITY_CODE;
	private String C97_AMOUNT_NET_SETTLEMENT;
	private String C98_PAYEE;
	private String C99_SETTLEMENT_INST_CODE;
	private String C100_RECV_INST_CODE;
	private String C101_FILE_NAME;
	private String C103_ACCOUNT_ID2;
	private String C102_ACCOUNT_ID1;
	private String C104_TRANS_DESCRIPTION;
	private String C105_RESERVED_ISO;
	private String C106_RESERVED_ISO;
	private String C107_RESERVED_ISO;
	private String C108_RESERVED_ISO;
	private String C109_RESERVED_ISO;
	private String C110_RESERVED_ISO;
	private String C111_RESERVED_ISO;
	private String C112_ADDITIONAL_DATA;
	private String C113_RESERVED_NATIONAL_USE;
	private String C114_RESERVED_NATIONAL_USE;
	private String C115_RESERVED_NATIONAL_USE;
	private String C116_RESERVED_NATIONAL_USE;
	private String C117_RESERVED_NATIONAL_USE;
	private String C118_RESERVED_NATIONAL_USE;
	private String C119_RESERVED_NATIONAL_USE;
	private String C120_RECORD_DATA;
	private String C121_AUTHORING_AGENT_ID;
	private String C122_ADDITIONAL_RECORD_DATA;
	private String C123_RESERVED;
	private String C124_RESERVED;
	private String C125_RESERVED;
	private String C126_PRIVATE_DATA;
	private String C127_PRIVATE_DATA;
	private String C128_MESSAG_AUTH_CODE;
	private String CERROR;
	
	public String getMSGTYPE() {
		return MSGTYPE;
	}
	public void setMSGTYPE(String mSGTYPE) {
		MSGTYPE = mSGTYPE;
	}
	public String getC2_TARJETA() {
		return C2_TARJETA;
	}
	public void setC2_TARJETA(String c2_TARJETA) {
		C2_TARJETA = c2_TARJETA;
	}
	public String getC3_PROCCODE() {
		return C3_PROCCODE;
	}
	public void setC3_PROCCODE(String c3_PROCCODE) {
		C3_PROCCODE = c3_PROCCODE;
	}
	public String getC4_MONTO() {
		return C4_MONTO;
	}
	public void setC4_MONTO(String c4_MONTO) {
		C4_MONTO = c4_MONTO;
	}
	public String getC5_MONTO_SETTLEMENT() {
		return C5_MONTO_SETTLEMENT;
	}
	public void setC5_MONTO_SETTLEMENT(String c5_MONTO_SETTLEMENT) {
		C5_MONTO_SETTLEMENT = c5_MONTO_SETTLEMENT;
	}
	public String getC6_MONTO_CARDBILL() {
		return C6_MONTO_CARDBILL;
	}
	public void setC6_MONTO_CARDBILL(String c6_MONTO_CARDBILL) {
		C6_MONTO_CARDBILL = c6_MONTO_CARDBILL;
	}
	public String getC7_DATETIME() {
		return C7_DATETIME;
	}
	public void setC7_DATETIME(String c7_DATETIME) {
		C7_DATETIME = c7_DATETIME;
	}
	public String getC8_MONTO_CARDBILLFEE() {
		return C8_MONTO_CARDBILLFEE;
	}
	public void setC8_MONTO_CARDBILLFEE(String c8_MONTO_CARDBILLFEE) {
		C8_MONTO_CARDBILLFEE = c8_MONTO_CARDBILLFEE;
	}
	public String getC9_CONVER_RATE_SETTLEMENT() {
		return C9_CONVER_RATE_SETTLEMENT;
	}
	public void setC9_CONVER_RATE_SETTLEMENT(String c9_CONVER_RATE_SETTLEMENT) {
		C9_CONVER_RATE_SETTLEMENT = c9_CONVER_RATE_SETTLEMENT;
	}
	public String getC10_CONVER_RATE_CARDBILL() {
		return C10_CONVER_RATE_CARDBILL;
	}
	public void setC10_CONVER_RATE_CARDBILL(String c10_CONVER_RATE_CARDBILL) {
		C10_CONVER_RATE_CARDBILL = c10_CONVER_RATE_CARDBILL;
	}
	public String getC11_AUDIT_NUMBER() {
		return C11_AUDIT_NUMBER;
	}
	public void setC11_AUDIT_NUMBER(String c11_AUDIT_NUMBER) {
		C11_AUDIT_NUMBER = c11_AUDIT_NUMBER;
	}
	public String getC12_HORA_TRAN() {
		return C12_HORA_TRAN;
	}
	public void setC12_HORA_TRAN(String c12_HORA_TRAN) {
		C12_HORA_TRAN = c12_HORA_TRAN;
	}
	public String getC13_FECHA_TRAN() {
		return C13_FECHA_TRAN;
	}
	public void setC13_FECHA_TRAN(String c13_FECHA_TRAN) {
		C13_FECHA_TRAN = c13_FECHA_TRAN;
	}
	public String getC14_EXP_DATE() {
		return C14_EXP_DATE;
	}
	public void setC14_EXP_DATE(String c14_EXP_DATE) {
		C14_EXP_DATE = c14_EXP_DATE;
	}
	public String getC15_DATE_SETTLEMENT() {
		return C15_DATE_SETTLEMENT;
	}
	public void setC15_DATE_SETTLEMENT(String c15_DATE_SETTLEMENT) {
		C15_DATE_SETTLEMENT = c15_DATE_SETTLEMENT;
	}
	public String getC16_DATE_CONVERSION() {
		return C16_DATE_CONVERSION;
	}
	public void setC16_DATE_CONVERSION(String c16_DATE_CONVERSION) {
		C16_DATE_CONVERSION = c16_DATE_CONVERSION;
	}
	public String getC17_DATE_CAPTURE() {
		return C17_DATE_CAPTURE;
	}
	public void setC17_DATE_CAPTURE(String c17_DATE_CAPTURE) {
		C17_DATE_CAPTURE = c17_DATE_CAPTURE;
	}
	public String getC18_MERCHANT_TYPE() {
		return C18_MERCHANT_TYPE;
	}
	public void setC18_MERCHANT_TYPE(String c18_MERCHANT_TYPE) {
		C18_MERCHANT_TYPE = c18_MERCHANT_TYPE;
	}
	public String getC19_ADQ_INST_COUTRY_CODE() {
		return C19_ADQ_INST_COUTRY_CODE;
	}
	public void setC19_ADQ_INST_COUTRY_CODE(String c19_ADQ_INST_COUTRY_CODE) {
		C19_ADQ_INST_COUTRY_CODE = c19_ADQ_INST_COUTRY_CODE;
	}
	public String getC20_PAN_COUNTRY_CODE() {
		return C20_PAN_COUNTRY_CODE;
	}
	public void setC20_PAN_COUNTRY_CODE(String c20_PAN_COUNTRY_CODE) {
		C20_PAN_COUNTRY_CODE = c20_PAN_COUNTRY_CODE;
	}
	public String getC21_FORW_INST_COUNTRY_CODE() {
		return C21_FORW_INST_COUNTRY_CODE;
	}
	public void setC21_FORW_INST_COUNTRY_CODE(String c21_FORW_INST_COUNTRY_CODE) {
		C21_FORW_INST_COUNTRY_CODE = c21_FORW_INST_COUNTRY_CODE;
	}
	public String getC22_POS_ENTRY_MODE() {
		return C22_POS_ENTRY_MODE;
	}
	public void setC22_POS_ENTRY_MODE(String c22_POS_ENTRY_MODE) {
		C22_POS_ENTRY_MODE = c22_POS_ENTRY_MODE;
	}
	public String getC23_CARD_SEQ_NUMBER() {
		return C23_CARD_SEQ_NUMBER;
	}
	public void setC23_CARD_SEQ_NUMBER(String c23_CARD_SEQ_NUMBER) {
		C23_CARD_SEQ_NUMBER = c23_CARD_SEQ_NUMBER;
	}
	public String getC24_NETWORK_ID() {
		return C24_NETWORK_ID;
	}
	public void setC24_NETWORK_ID(String c24_NETWORK_ID) {
		C24_NETWORK_ID = c24_NETWORK_ID;
	}
	public String getC25_POS_COND_CODE() {
		return C25_POS_COND_CODE;
	}
	public void setC25_POS_COND_CODE(String c25_POS_COND_CODE) {
		C25_POS_COND_CODE = c25_POS_COND_CODE;
	}
	public String getC26_POS_PIN_CAPTURE_CODE() {
		return C26_POS_PIN_CAPTURE_CODE;
	}
	public void setC26_POS_PIN_CAPTURE_CODE(String c26_POS_PIN_CAPTURE_CODE) {
		C26_POS_PIN_CAPTURE_CODE = c26_POS_PIN_CAPTURE_CODE;
	}
	public String getC27_AUTH_RESPONSE_LENGTH() {
		return C27_AUTH_RESPONSE_LENGTH;
	}
	public void setC27_AUTH_RESPONSE_LENGTH(String c27_AUTH_RESPONSE_LENGTH) {
		C27_AUTH_RESPONSE_LENGTH = c27_AUTH_RESPONSE_LENGTH;
	}
	public String getC28_MONTO_TRANS_FEE() {
		return C28_MONTO_TRANS_FEE;
	}
	public void setC28_MONTO_TRANS_FEE(String c28_MONTO_TRANS_FEE) {
		C28_MONTO_TRANS_FEE = c28_MONTO_TRANS_FEE;
	}
	public String getC29_MONTO_SETTLEMENT_FEE() {
		return C29_MONTO_SETTLEMENT_FEE;
	}
	public void setC29_MONTO_SETTLEMENT_FEE(String c29_MONTO_SETTLEMENT_FEE) {
		C29_MONTO_SETTLEMENT_FEE = c29_MONTO_SETTLEMENT_FEE;
	}
	public String getC30_MONTO_TRANS_PROC_FEE() {
		return C30_MONTO_TRANS_PROC_FEE;
	}
	public void setC30_MONTO_TRANS_PROC_FEE(String c30_MONTO_TRANS_PROC_FEE) {
		C30_MONTO_TRANS_PROC_FEE = c30_MONTO_TRANS_PROC_FEE;
	}
	public String getC31_MONTO_SETTLEMENT_PROC_FEE() {
		return C31_MONTO_SETTLEMENT_PROC_FEE;
	}
	public void setC31_MONTO_SETTLEMENT_PROC_FEE(String c31_MONTO_SETTLEMENT_PROC_FEE) {
		C31_MONTO_SETTLEMENT_PROC_FEE = c31_MONTO_SETTLEMENT_PROC_FEE;
	}
	public String getC32_ACQ_INST_ID() {
		return C32_ACQ_INST_ID;
	}
	public void setC32_ACQ_INST_ID(String c32_ACQ_INST_ID) {
		C32_ACQ_INST_ID = c32_ACQ_INST_ID;
	}
	public String getC33_FORW_INST_ID() {
		return C33_FORW_INST_ID;
	}
	public void setC33_FORW_INST_ID(String c33_FORW_INST_ID) {
		C33_FORW_INST_ID = c33_FORW_INST_ID;
	}
	public String getC34_PAN_EXTENDED() {
		return C34_PAN_EXTENDED;
	}
	public void setC34_PAN_EXTENDED(String c34_PAN_EXTENDED) {
		C34_PAN_EXTENDED = c34_PAN_EXTENDED;
	}
	public String getC35_TRACK2() {
		return C35_TRACK2;
	}
	public void setC35_TRACK2(String c35_TRACK2) {
		C35_TRACK2 = c35_TRACK2;
	}
	public String getC36_TRACK3() {
		return C36_TRACK3;
	}
	public void setC36_TRACK3(String c36_TRACK3) {
		C36_TRACK3 = c36_TRACK3;
	}
	public String getC37_REFERENCE_NUMBER() {
		return C37_REFERENCE_NUMBER;
	}
	public void setC37_REFERENCE_NUMBER(String c37_REFERENCE_NUMBER) {
		C37_REFERENCE_NUMBER = c37_REFERENCE_NUMBER;
	}
	public String getC38_AUTORIZACION() {
		return C38_AUTORIZACION;
	}
	public void setC38_AUTORIZACION(String c38_AUTORIZACION) {
		C38_AUTORIZACION = c38_AUTORIZACION;
	}
	public String getC39_RESP_CODE() {
		return C39_RESP_CODE;
	}
	public void setC39_RESP_CODE(String c39_RESP_CODE) {
		C39_RESP_CODE = c39_RESP_CODE;
	}
	public String getC40_SERV_RESTRICTION_CODE() {
		return C40_SERV_RESTRICTION_CODE;
	}
	public void setC40_SERV_RESTRICTION_CODE(String c40_SERV_RESTRICTION_CODE) {
		C40_SERV_RESTRICTION_CODE = c40_SERV_RESTRICTION_CODE;
	}
	public String getC41_TERMINAL_ID() {
		return C41_TERMINAL_ID;
	}
	public void setC41_TERMINAL_ID(String c41_TERMINAL_ID) {
		C41_TERMINAL_ID = c41_TERMINAL_ID;
	}
	public String getC42_CARD_ACCEPTOR_ID() {
		return C42_CARD_ACCEPTOR_ID;
	}
	public void setC42_CARD_ACCEPTOR_ID(String c42_CARD_ACCEPTOR_ID) {
		C42_CARD_ACCEPTOR_ID = c42_CARD_ACCEPTOR_ID;
	}
	public String getC43_CARD_ACCEPTOR_NAME_LOC() {
		return C43_CARD_ACCEPTOR_NAME_LOC;
	}
	public void setC43_CARD_ACCEPTOR_NAME_LOC(String c43_CARD_ACCEPTOR_NAME_LOC) {
		C43_CARD_ACCEPTOR_NAME_LOC = c43_CARD_ACCEPTOR_NAME_LOC;
	}
	public String getC44_ADDITIONAL_RESP_DATA() {
		return C44_ADDITIONAL_RESP_DATA;
	}
	public void setC44_ADDITIONAL_RESP_DATA(String c44_ADDITIONAL_RESP_DATA) {
		C44_ADDITIONAL_RESP_DATA = c44_ADDITIONAL_RESP_DATA;
	}
	public String getC45_TRACK1() {
		return C45_TRACK1;
	}
	public void setC45_TRACK1(String c45_TRACK1) {
		C45_TRACK1 = c45_TRACK1;
	}
	public String getC46_ADDITIONAL_DATA_ISO_USE() {
		return C46_ADDITIONAL_DATA_ISO_USE;
	}
	public void setC46_ADDITIONAL_DATA_ISO_USE(String c46_ADDITIONAL_DATA_ISO_USE) {
		C46_ADDITIONAL_DATA_ISO_USE = c46_ADDITIONAL_DATA_ISO_USE;
	}
	public String getC47_ADDITIONAL_DATA_NAT_USE() {
		return C47_ADDITIONAL_DATA_NAT_USE;
	}
	public void setC47_ADDITIONAL_DATA_NAT_USE(String c47_ADDITIONAL_DATA_NAT_USE) {
		C47_ADDITIONAL_DATA_NAT_USE = c47_ADDITIONAL_DATA_NAT_USE;
	}
	public String getC48_ADDITIONAL_DATA_PRIV_USE() {
		return C48_ADDITIONAL_DATA_PRIV_USE;
	}
	public void setC48_ADDITIONAL_DATA_PRIV_USE(String c48_ADDITIONAL_DATA_PRIV_USE) {
		C48_ADDITIONAL_DATA_PRIV_USE = c48_ADDITIONAL_DATA_PRIV_USE;
	}
	public String getC49_CURRENCY_CODE() {
		return C49_CURRENCY_CODE;
	}
	public void setC49_CURRENCY_CODE(String c49_CURRENCY_CODE) {
		C49_CURRENCY_CODE = c49_CURRENCY_CODE;
	}
	public String getC50_CURRENCY_CODE_SETTLEMENT() {
		return C50_CURRENCY_CODE_SETTLEMENT;
	}
	public void setC50_CURRENCY_CODE_SETTLEMENT(String c50_CURRENCY_CODE_SETTLEMENT) {
		C50_CURRENCY_CODE_SETTLEMENT = c50_CURRENCY_CODE_SETTLEMENT;
	}
	public String getC51_CURRENCY_CODE_CARDBILL() {
		return C51_CURRENCY_CODE_CARDBILL;
	}
	public void setC51_CURRENCY_CODE_CARDBILL(String c51_CURRENCY_CODE_CARDBILL) {
		C51_CURRENCY_CODE_CARDBILL = c51_CURRENCY_CODE_CARDBILL;
	}
	public String getC52_PIN_DATA() {
		return C52_PIN_DATA;
	}
	public void setC52_PIN_DATA(String c52_PIN_DATA) {
		C52_PIN_DATA = c52_PIN_DATA;
	}
	public String getC53_SECURITY_RELATE_INF() {
		return C53_SECURITY_RELATE_INF;
	}
	public void setC53_SECURITY_RELATE_INF(String c53_SECURITY_RELATE_INF) {
		C53_SECURITY_RELATE_INF = c53_SECURITY_RELATE_INF;
	}
	public String getC54_ADDITIONAL_AMOUNTS() {
		return C54_ADDITIONAL_AMOUNTS;
	}
	public void setC54_ADDITIONAL_AMOUNTS(String c54_ADDITIONAL_AMOUNTS) {
		C54_ADDITIONAL_AMOUNTS = c54_ADDITIONAL_AMOUNTS;
	}
	public String getC55_ICC_SYSTEM() {
		return C55_ICC_SYSTEM;
	}
	public void setC55_ICC_SYSTEM(String c55_ICC_SYSTEM) {
		C55_ICC_SYSTEM = c55_ICC_SYSTEM;
	}
	public String getC56_RESERVED_ISO() {
		return C56_RESERVED_ISO;
	}
	public void setC56_RESERVED_ISO(String c56_RESERVED_ISO) {
		C56_RESERVED_ISO = c56_RESERVED_ISO;
	}
	public String getC57_RESERVED_NATIONAL_USE() {
		return C57_RESERVED_NATIONAL_USE;
	}
	public void setC57_RESERVED_NATIONAL_USE(String c57_RESERVED_NATIONAL_USE) {
		C57_RESERVED_NATIONAL_USE = c57_RESERVED_NATIONAL_USE;
	}
	public String getC58_RESERVED_NATIONAL_USE() {
		return C58_RESERVED_NATIONAL_USE;
	}
	public void setC58_RESERVED_NATIONAL_USE(String c58_RESERVED_NATIONAL_USE) {
		C58_RESERVED_NATIONAL_USE = c58_RESERVED_NATIONAL_USE;
	}
	public String getC59_NAT_GEO_DATA() {
		return C59_NAT_GEO_DATA;
	}
	public void setC59_NAT_GEO_DATA(String c59_NAT_GEO_DATA) {
		C59_NAT_GEO_DATA = c59_NAT_GEO_DATA;
	}
	public String getC60_ADVICE_REASON_CODE() {
		return C60_ADVICE_REASON_CODE;
	}
	public void setC60_ADVICE_REASON_CODE(String c60_ADVICE_REASON_CODE) {
		C60_ADVICE_REASON_CODE = c60_ADVICE_REASON_CODE;
	}
	public String getC61_POS_DATA() {
		return C61_POS_DATA;
	}
	public void setC61_POS_DATA(String c61_POS_DATA) {
		C61_POS_DATA = c61_POS_DATA;
	}
	public String getC62_INT_NETWORK_FACILITY_DATA() {
		return C62_INT_NETWORK_FACILITY_DATA;
	}
	public void setC62_INT_NETWORK_FACILITY_DATA(String c62_INT_NETWORK_FACILITY_DATA) {
		C62_INT_NETWORK_FACILITY_DATA = c62_INT_NETWORK_FACILITY_DATA;
	}
	public String getC63_BANKNET_DATA() {
		return C63_BANKNET_DATA;
	}
	public void setC63_BANKNET_DATA(String c63_BANKNET_DATA) {
		C63_BANKNET_DATA = c63_BANKNET_DATA;
	}
	public String getC64_MESSAGE_AUTH_CODE() {
		return C64_MESSAGE_AUTH_CODE;
	}
	public void setC64_MESSAGE_AUTH_CODE(String c64_MESSAGE_AUTH_CODE) {
		C64_MESSAGE_AUTH_CODE = c64_MESSAGE_AUTH_CODE;
	}
	public String getC65_BITMAP_EXTENDED() {
		return C65_BITMAP_EXTENDED;
	}
	public void setC65_BITMAP_EXTENDED(String c65_BITMAP_EXTENDED) {
		C65_BITMAP_EXTENDED = c65_BITMAP_EXTENDED;
	}
	public String getC66_SETTLEMENT_CODE() {
		return C66_SETTLEMENT_CODE;
	}
	public void setC66_SETTLEMENT_CODE(String c66_SETTLEMENT_CODE) {
		C66_SETTLEMENT_CODE = c66_SETTLEMENT_CODE;
	}
	public String getC67_EXTENDED_PAYMENT_CODE() {
		return C67_EXTENDED_PAYMENT_CODE;
	}
	public void setC67_EXTENDED_PAYMENT_CODE(String c67_EXTENDED_PAYMENT_CODE) {
		C67_EXTENDED_PAYMENT_CODE = c67_EXTENDED_PAYMENT_CODE;
	}
	public String getC68_RECV_INST_COUNTRY_CODE() {
		return C68_RECV_INST_COUNTRY_CODE;
	}
	public void setC68_RECV_INST_COUNTRY_CODE(String c68_RECV_INST_COUNTRY_CODE) {
		C68_RECV_INST_COUNTRY_CODE = c68_RECV_INST_COUNTRY_CODE;
	}
	public String getC69_SETTL_INST_COUNTRY_CODE() {
		return C69_SETTL_INST_COUNTRY_CODE;
	}
	public void setC69_SETTL_INST_COUNTRY_CODE(String c69_SETTL_INST_COUNTRY_CODE) {
		C69_SETTL_INST_COUNTRY_CODE = c69_SETTL_INST_COUNTRY_CODE;
	}
	public String getC70_NET_INFORMATION_CODE() {
		return C70_NET_INFORMATION_CODE;
	}
	public void setC70_NET_INFORMATION_CODE(String c70_NET_INFORMATION_CODE) {
		C70_NET_INFORMATION_CODE = c70_NET_INFORMATION_CODE;
	}
	public String getC71_MESSAGE_NUMBER() {
		return C71_MESSAGE_NUMBER;
	}
	public void setC71_MESSAGE_NUMBER(String c71_MESSAGE_NUMBER) {
		C71_MESSAGE_NUMBER = c71_MESSAGE_NUMBER;
	}
	public String getC72_MESSAGE_NUMBER_LAST() {
		return C72_MESSAGE_NUMBER_LAST;
	}
	public void setC72_MESSAGE_NUMBER_LAST(String c72_MESSAGE_NUMBER_LAST) {
		C72_MESSAGE_NUMBER_LAST = c72_MESSAGE_NUMBER_LAST;
	}
	public String getC73_DATE_ACTION() {
		return C73_DATE_ACTION;
	}
	public void setC73_DATE_ACTION(String c73_DATE_ACTION) {
		C73_DATE_ACTION = c73_DATE_ACTION;
	}
	public String getC74_CREDITS_NUMBER() {
		return C74_CREDITS_NUMBER;
	}
	public void setC74_CREDITS_NUMBER(String c74_CREDITS_NUMBER) {
		C74_CREDITS_NUMBER = c74_CREDITS_NUMBER;
	}
	public String getC75_CREDITS_REVERSAL_NUMBER() {
		return C75_CREDITS_REVERSAL_NUMBER;
	}
	public void setC75_CREDITS_REVERSAL_NUMBER(String c75_CREDITS_REVERSAL_NUMBER) {
		C75_CREDITS_REVERSAL_NUMBER = c75_CREDITS_REVERSAL_NUMBER;
	}
	public String getC76_DEBITS_NUMBER() {
		return C76_DEBITS_NUMBER;
	}
	public void setC76_DEBITS_NUMBER(String c76_DEBITS_NUMBER) {
		C76_DEBITS_NUMBER = c76_DEBITS_NUMBER;
	}
	public String getC77_DEBITS_REVERSAL_NUMBER() {
		return C77_DEBITS_REVERSAL_NUMBER;
	}
	public void setC77_DEBITS_REVERSAL_NUMBER(String c77_DEBITS_REVERSAL_NUMBER) {
		C77_DEBITS_REVERSAL_NUMBER = c77_DEBITS_REVERSAL_NUMBER;
	}
	public String getC78_TRANSFERS_NUMBER() {
		return C78_TRANSFERS_NUMBER;
	}
	public void setC78_TRANSFERS_NUMBER(String c78_TRANSFERS_NUMBER) {
		C78_TRANSFERS_NUMBER = c78_TRANSFERS_NUMBER;
	}
	public String getC79_TRANSFERS_REVERSAL_NUMBER() {
		return C79_TRANSFERS_REVERSAL_NUMBER;
	}
	public void setC79_TRANSFERS_REVERSAL_NUMBER(String c79_TRANSFERS_REVERSAL_NUMBER) {
		C79_TRANSFERS_REVERSAL_NUMBER = c79_TRANSFERS_REVERSAL_NUMBER;
	}
	public String getC80_INQUIRIES_NUMBER() {
		return C80_INQUIRIES_NUMBER;
	}
	public void setC80_INQUIRIES_NUMBER(String c80_INQUIRIES_NUMBER) {
		C80_INQUIRIES_NUMBER = c80_INQUIRIES_NUMBER;
	}
	public String getC81_AUTHORIZATION_NUMBER() {
		return C81_AUTHORIZATION_NUMBER;
	}
	public void setC81_AUTHORIZATION_NUMBER(String c81_AUTHORIZATION_NUMBER) {
		C81_AUTHORIZATION_NUMBER = c81_AUTHORIZATION_NUMBER;
	}
	public String getC82_CREDITS_PROC_FEE_AMOUNT() {
		return C82_CREDITS_PROC_FEE_AMOUNT;
	}
	public void setC82_CREDITS_PROC_FEE_AMOUNT(String c82_CREDITS_PROC_FEE_AMOUNT) {
		C82_CREDITS_PROC_FEE_AMOUNT = c82_CREDITS_PROC_FEE_AMOUNT;
	}
	public String getC83_CREDITS_TRAN_FEE_AMOUNT() {
		return C83_CREDITS_TRAN_FEE_AMOUNT;
	}
	public void setC83_CREDITS_TRAN_FEE_AMOUNT(String c83_CREDITS_TRAN_FEE_AMOUNT) {
		C83_CREDITS_TRAN_FEE_AMOUNT = c83_CREDITS_TRAN_FEE_AMOUNT;
	}
	public String getC84_DEBITS_PROC_FEE_AMOUNT() {
		return C84_DEBITS_PROC_FEE_AMOUNT;
	}
	public void setC84_DEBITS_PROC_FEE_AMOUNT(String c84_DEBITS_PROC_FEE_AMOUNT) {
		C84_DEBITS_PROC_FEE_AMOUNT = c84_DEBITS_PROC_FEE_AMOUNT;
	}
	public String getC85_DEBITS_TRAN_FEE_AMOUNT() {
		return C85_DEBITS_TRAN_FEE_AMOUNT;
	}
	public void setC85_DEBITS_TRAN_FEE_AMOUNT(String c85_DEBITS_TRAN_FEE_AMOUNT) {
		C85_DEBITS_TRAN_FEE_AMOUNT = c85_DEBITS_TRAN_FEE_AMOUNT;
	}
	public String getC86_CREDITS_AMOUNT() {
		return C86_CREDITS_AMOUNT;
	}
	public void setC86_CREDITS_AMOUNT(String c86_CREDITS_AMOUNT) {
		C86_CREDITS_AMOUNT = c86_CREDITS_AMOUNT;
	}
	public String getC87_CREDITS_REVERSAL_AMOUNT() {
		return C87_CREDITS_REVERSAL_AMOUNT;
	}
	public void setC87_CREDITS_REVERSAL_AMOUNT(String c87_CREDITS_REVERSAL_AMOUNT) {
		C87_CREDITS_REVERSAL_AMOUNT = c87_CREDITS_REVERSAL_AMOUNT;
	}
	public String getC88_DEBITS_AMOUNT() {
		return C88_DEBITS_AMOUNT;
	}
	public void setC88_DEBITS_AMOUNT(String c88_DEBITS_AMOUNT) {
		C88_DEBITS_AMOUNT = c88_DEBITS_AMOUNT;
	}
	public String getC89_DEBITS_REVERSAL_AMOUNT() {
		return C89_DEBITS_REVERSAL_AMOUNT;
	}
	public void setC89_DEBITS_REVERSAL_AMOUNT(String c89_DEBITS_REVERSAL_AMOUNT) {
		C89_DEBITS_REVERSAL_AMOUNT = c89_DEBITS_REVERSAL_AMOUNT;
	}
	public String getC90_ORIGINAL_DATA() {
		return C90_ORIGINAL_DATA;
	}
	public void setC90_ORIGINAL_DATA(String c90_ORIGINAL_DATA) {
		C90_ORIGINAL_DATA = c90_ORIGINAL_DATA;
	}
	public String getC91_FILE_UPDATE_CODE() {
		return C91_FILE_UPDATE_CODE;
	}
	public void setC91_FILE_UPDATE_CODE(String c91_FILE_UPDATE_CODE) {
		C91_FILE_UPDATE_CODE = c91_FILE_UPDATE_CODE;
	}
	public String getC92_FILE_SECURITY_CODE() {
		return C92_FILE_SECURITY_CODE;
	}
	public void setC92_FILE_SECURITY_CODE(String c92_FILE_SECURITY_CODE) {
		C92_FILE_SECURITY_CODE = c92_FILE_SECURITY_CODE;
	}
	public String getC93_RESPONSE_INDICATOR() {
		return C93_RESPONSE_INDICATOR;
	}
	public void setC93_RESPONSE_INDICATOR(String c93_RESPONSE_INDICATOR) {
		C93_RESPONSE_INDICATOR = c93_RESPONSE_INDICATOR;
	}
	public String getC94_SERVICE_INDICATOR() {
		return C94_SERVICE_INDICATOR;
	}
	public void setC94_SERVICE_INDICATOR(String c94_SERVICE_INDICATOR) {
		C94_SERVICE_INDICATOR = c94_SERVICE_INDICATOR;
	}
	public String getC95_REPLACEMENT_AMOUNTS() {
		return C95_REPLACEMENT_AMOUNTS;
	}
	public void setC95_REPLACEMENT_AMOUNTS(String c95_REPLACEMENT_AMOUNTS) {
		C95_REPLACEMENT_AMOUNTS = c95_REPLACEMENT_AMOUNTS;
	}
	public String getC96_MESSAGE_SECURITY_CODE() {
		return C96_MESSAGE_SECURITY_CODE;
	}
	public void setC96_MESSAGE_SECURITY_CODE(String c96_MESSAGE_SECURITY_CODE) {
		C96_MESSAGE_SECURITY_CODE = c96_MESSAGE_SECURITY_CODE;
	}
	public String getC97_AMOUNT_NET_SETTLEMENT() {
		return C97_AMOUNT_NET_SETTLEMENT;
	}
	public void setC97_AMOUNT_NET_SETTLEMENT(String c97_AMOUNT_NET_SETTLEMENT) {
		C97_AMOUNT_NET_SETTLEMENT = c97_AMOUNT_NET_SETTLEMENT;
	}
	public String getC98_PAYEE() {
		return C98_PAYEE;
	}
	public void setC98_PAYEE(String c98_PAYEE) {
		C98_PAYEE = c98_PAYEE;
	}
	public String getC99_SETTLEMENT_INST_CODE() {
		return C99_SETTLEMENT_INST_CODE;
	}
	public void setC99_SETTLEMENT_INST_CODE(String c99_SETTLEMENT_INST_CODE) {
		C99_SETTLEMENT_INST_CODE = c99_SETTLEMENT_INST_CODE;
	}
	public String getC100_RECV_INST_CODE() {
		return C100_RECV_INST_CODE;
	}
	public void setC100_RECV_INST_CODE(String c100_RECV_INST_CODE) {
		C100_RECV_INST_CODE = c100_RECV_INST_CODE;
	}
	public String getC101_FILE_NAME() {
		return C101_FILE_NAME;
	}
	public void setC101_FILE_NAME(String c101_FILE_NAME) {
		C101_FILE_NAME = c101_FILE_NAME;
	}
	public String getC103_ACCOUNT_ID2() {
		return C103_ACCOUNT_ID2;
	}
	public void setC103_ACCOUNT_ID2(String c103_ACCOUNT_ID2) {
		C103_ACCOUNT_ID2 = c103_ACCOUNT_ID2;
	}
	public String getC102_ACCOUNT_ID1() {
		return C102_ACCOUNT_ID1;
	}
	public void setC102_ACCOUNT_ID1(String c102_ACCOUNT_ID1) {
		C102_ACCOUNT_ID1 = c102_ACCOUNT_ID1;
	}
	public String getC104_TRANS_DESCRIPTION() {
		return C104_TRANS_DESCRIPTION;
	}
	public void setC104_TRANS_DESCRIPTION(String c104_TRANS_DESCRIPTION) {
		C104_TRANS_DESCRIPTION = c104_TRANS_DESCRIPTION;
	}
	public String getC105_RESERVED_ISO() {
		return C105_RESERVED_ISO;
	}
	public void setC105_RESERVED_ISO(String c105_RESERVED_ISO) {
		C105_RESERVED_ISO = c105_RESERVED_ISO;
	}
	public String getC106_RESERVED_ISO() {
		return C106_RESERVED_ISO;
	}
	public void setC106_RESERVED_ISO(String c106_RESERVED_ISO) {
		C106_RESERVED_ISO = c106_RESERVED_ISO;
	}
	public String getC107_RESERVED_ISO() {
		return C107_RESERVED_ISO;
	}
	public void setC107_RESERVED_ISO(String c107_RESERVED_ISO) {
		C107_RESERVED_ISO = c107_RESERVED_ISO;
	}
	public String getC108_RESERVED_ISO() {
		return C108_RESERVED_ISO;
	}
	public void setC108_RESERVED_ISO(String c108_RESERVED_ISO) {
		C108_RESERVED_ISO = c108_RESERVED_ISO;
	}
	public String getC109_RESERVED_ISO() {
		return C109_RESERVED_ISO;
	}
	public void setC109_RESERVED_ISO(String c109_RESERVED_ISO) {
		C109_RESERVED_ISO = c109_RESERVED_ISO;
	}
	public String getC110_RESERVED_ISO() {
		return C110_RESERVED_ISO;
	}
	public void setC110_RESERVED_ISO(String c110_RESERVED_ISO) {
		C110_RESERVED_ISO = c110_RESERVED_ISO;
	}
	public String getC111_RESERVED_ISO() {
		return C111_RESERVED_ISO;
	}
	public void setC111_RESERVED_ISO(String c111_RESERVED_ISO) {
		C111_RESERVED_ISO = c111_RESERVED_ISO;
	}
	public String getC112_ADDITIONAL_DATA() {
		return C112_ADDITIONAL_DATA;
	}
	public void setC112_ADDITIONAL_DATA(String c112_ADDITIONAL_DATA) {
		C112_ADDITIONAL_DATA = c112_ADDITIONAL_DATA;
	}
	public String getC113_RESERVED_NATIONAL_USE() {
		return C113_RESERVED_NATIONAL_USE;
	}
	public void setC113_RESERVED_NATIONAL_USE(String c113_RESERVED_NATIONAL_USE) {
		C113_RESERVED_NATIONAL_USE = c113_RESERVED_NATIONAL_USE;
	}
	public String getC114_RESERVED_NATIONAL_USE() {
		return C114_RESERVED_NATIONAL_USE;
	}
	public void setC114_RESERVED_NATIONAL_USE(String c114_RESERVED_NATIONAL_USE) {
		C114_RESERVED_NATIONAL_USE = c114_RESERVED_NATIONAL_USE;
	}
	public String getC115_RESERVED_NATIONAL_USE() {
		return C115_RESERVED_NATIONAL_USE;
	}
	public void setC115_RESERVED_NATIONAL_USE(String c115_RESERVED_NATIONAL_USE) {
		C115_RESERVED_NATIONAL_USE = c115_RESERVED_NATIONAL_USE;
	}
	public String getC116_RESERVED_NATIONAL_USE() {
		return C116_RESERVED_NATIONAL_USE;
	}
	public void setC116_RESERVED_NATIONAL_USE(String c116_RESERVED_NATIONAL_USE) {
		C116_RESERVED_NATIONAL_USE = c116_RESERVED_NATIONAL_USE;
	}
	public String getC117_RESERVED_NATIONAL_USE() {
		return C117_RESERVED_NATIONAL_USE;
	}
	public void setC117_RESERVED_NATIONAL_USE(String c117_RESERVED_NATIONAL_USE) {
		C117_RESERVED_NATIONAL_USE = c117_RESERVED_NATIONAL_USE;
	}
	public String getC118_RESERVED_NATIONAL_USE() {
		return C118_RESERVED_NATIONAL_USE;
	}
	public void setC118_RESERVED_NATIONAL_USE(String c118_RESERVED_NATIONAL_USE) {
		C118_RESERVED_NATIONAL_USE = c118_RESERVED_NATIONAL_USE;
	}
	public String getC119_RESERVED_NATIONAL_USE() {
		return C119_RESERVED_NATIONAL_USE;
	}
	public void setC119_RESERVED_NATIONAL_USE(String c119_RESERVED_NATIONAL_USE) {
		C119_RESERVED_NATIONAL_USE = c119_RESERVED_NATIONAL_USE;
	}
	public String getC120_RECORD_DATA() {
		return C120_RECORD_DATA;
	}
	public void setC120_RECORD_DATA(String c120_RECORD_DATA) {
		C120_RECORD_DATA = c120_RECORD_DATA;
	}
	public String getC121_AUTHORING_AGENT_ID() {
		return C121_AUTHORING_AGENT_ID;
	}
	public void setC121_AUTHORING_AGENT_ID(String c121_AUTHORING_AGENT_ID) {
		C121_AUTHORING_AGENT_ID = c121_AUTHORING_AGENT_ID;
	}
	public String getC122_ADDITIONAL_RECORD_DATA() {
		return C122_ADDITIONAL_RECORD_DATA;
	}
	public void setC122_ADDITIONAL_RECORD_DATA(String c122_ADDITIONAL_RECORD_DATA) {
		C122_ADDITIONAL_RECORD_DATA = c122_ADDITIONAL_RECORD_DATA;
	}
	public String getC123_RESERVED() {
		return C123_RESERVED;
	}
	public void setC123_RESERVED(String c123_RESERVED) {
		C123_RESERVED = c123_RESERVED;
	}
	public String getC124_RESERVED() {
		return C124_RESERVED;
	}
	public void setC124_RESERVED(String c124_RESERVED) {
		C124_RESERVED = c124_RESERVED;
	}
	public String getC125_RESERVED() {
		return C125_RESERVED;
	}
	public void setC125_RESERVED(String c125_RESERVED) {
		C125_RESERVED = c125_RESERVED;
	}
	public String getC126_PRIVATE_DATA() {
		return C126_PRIVATE_DATA;
	}
	public void setC126_PRIVATE_DATA(String c126_PRIVATE_DATA) {
		C126_PRIVATE_DATA = c126_PRIVATE_DATA;
	}
	public String getC127_PRIVATE_DATA() {
		return C127_PRIVATE_DATA;
	}
	public void setC127_PRIVATE_DATA(String c127_PRIVATE_DATA) {
		C127_PRIVATE_DATA = c127_PRIVATE_DATA;
	}
	public String getC128_MESSAG_AUTH_CODE() {
		return C128_MESSAG_AUTH_CODE;
	}
	public void setC128_MESSAG_AUTH_CODE(String c128_MESSAG_AUTH_CODE) {
		C128_MESSAG_AUTH_CODE = c128_MESSAG_AUTH_CODE;
	}
	public String getCERROR() {
		return CERROR;
	}
	public void setCERROR(String cERROR) {
		CERROR = cERROR;
	}		
	
}
